Add test workflow with unittest (#189)
* Add `.gitignore`

* Add github test workflow

* Add push trigger

* Add expected failures and skips

* Also test on python version 3.11

* Remove python version 3.11 due to dependency error

* Add note on how to run tests

* Add `tf-keras` as a dependency

* Add expect failure for several tests and test classes all suffering from `AttributeError: module 'tensorflow_model_analysis' has no attribute 'EvalConfig'`

These are to be addressed in a future PR

* Remove import to nonexistant modules

* Install `libprotobuf-c-dev` for unit tests in CI

* Temporarily remove `expectedFailure`s

* Fix `EvalConfig` imports

* Add more `expectedFailure`s

* Remove `unexpectedFailure` from unexpected success

* Add Python 3.11 to CI tests

* Remove `libprotobuf-c-dev`

* Remove unnecessary import

* Add `expectedFailure`

* Use `skip` instead of `expectedFailure`

* Fix code comment

* Run for all users

---------

Co-authored-by: Peyton Murray <peynmurray@gmail.com>